concourse/resources/ecsNotify/README.md, concourse/resources/ecsNotify/code/deployBackEnd.js, dataCenter/singleEcs.json
This will break all current deployments but only once a docker image of it has been made and pushed to the hub. Everything will work fine until then.
=> 91 get task names from stack

concourse/resources/ecsNotify/README.md, concourse/resources/ecsNotify/code/deployBackEnd.js, dataCenter/singleEcs.json
Connects the stack to the two databases
=> Connect template to dbs

dataCenter/singleEcs.json
These were several small tweaks to the template, didn't make sense to create a branch per issue. 
* Parameterising the ec2 instances ssh key pair
* Adding a description to the template
* Assignment of elastic IP is not attempted if "null" is given as the ip
The IP checking is not ideal but parameter conditions seem to be broke AF which i've detailed in the JIRA issue
=> Template style tweaks

TrelloParseAndUpload/TrelloComms/App.config, TrelloParseAndUpload/TrelloComms/AssemblyInfo.fs, TrelloParseAndUpload/TrelloComms/CommsReader.fs, TrelloParseAndUpload/TrelloComms/Program.fs, TrelloParseAndUpload/TrelloComms/TrelloComms.fsproj, TrelloParseAndUpload/TrelloComms/packages.config, TrelloParseAndUpload/TrelloParser.sln, TrelloParseAndUpload/TrelloParser/DbRepository.fs, TrelloParseAndUpload/TrelloParser/Program.fs, TrelloParseAndUpload/TrelloParser/TrelloParser.fsproj, TrelloParseAndUpload/TrelloParser/TrelloReader.fs
Merge original version of trello sync for historical tracking
=> 60 historical speaker correspondance

dataCenter/singleEcs.json
If it remains as easy as this to add a service to the stack we'll be laughing
=> Added api docs docker image as a service within the cluster

dataCenter/singleEcs.json
=> Rename speakers endpoint

TrelloSync/TrelloSync/Actions.fs, TrelloSync/TrelloSync/Board.fs, TrelloSync/TrelloSync/Cards.fs, TrelloSync/TrelloSync/Download.fs, TrelloSync/TrelloSync/JsonToTypeWebClient.fs, TrelloSync/TrelloSync/Members.fs, TrelloSync/TrelloSync/TrelloSync.fsproj
It will be simpler to look at the two commits separately.
The first is the original pull request.
The second deals with the comment of reusing the web request code.
=> Trello sync/fetch card actions

dataCenter/singleEcs.json
Front end is on a separate cluster with it's on EC2 instance
=> BRITECH-194 Added front end to cloud formation template in new cluster

TrelloSync/TrelloSync/App.config, TrelloSync/TrelloSync/BoardParser.fs, TrelloSync/TrelloSync/CardParser.fs, TrelloSync/TrelloSync/CommsActionParser.fs, TrelloSync/TrelloSync/Credentials.fs, TrelloSync/TrelloSync/Helpers.fs, TrelloSync/TrelloSync/Import.fs, TrelloSync/TrelloSync/Logging.fs, TrelloSync/TrelloSync/Program.fs, TrelloSync/TrelloSync/SrmApiClient.fs, TrelloSync/TrelloSync/TrelloSync.fsproj, TrelloSync/TrelloSync/packages.config
Note: Main changes are in Import.fs
All other changes are just updating the logging to use Serilog.
=> Complete functionailty of TrelloSync V1

dataCenter/singleEcs.json
Removing everything except the frontend from ECS as the services are now on docker swarm.
=> Britech-347

TrelloSync/TrelloSync/Import.fs, TrelloSync/TrelloSync/SrmApiClient.fs, TrelloSync/TrelloSync/SrmApiModels.fs
Don't actually run it until we have local database, we don't want to update any data in any remote database at the moment.
=> Update sessions, correspondence and profiles models

dataCenter/chef/createChef.sh, dataCenter/chef/srm-chef.json
Master, with https access, chef-master pkg installed
One example node, chef client pkg installed
=> CloudFormation template and wrapper script

dataCenter/chef/README.md, dataCenter/chef/cookbooks/srm-docker/Berksfile, dataCenter/chef/cookbooks/srm-docker/README.md, dataCenter/chef/cookbooks/srm-docker/metadata.rb, dataCenter/chef/cookbooks/srm-docker/recipes/default.rb
README for setting up Chef.
Recipe for installing the docker daemon on the node.
=> Install docker

dataCenter/ansible/README.md, dataCenter/ansible/Vagrantfile, dataCenter/ansible/bootstrap-mgmt.sh
=> Create a management node

dataCenter/ansible/Vagrantfile, dataCenter/ansible/bootstrap-mgmt.sh
/etc/hosts must match the Vagrantfile IPs
=> Bare nodes

dataCenter/ansible/README.md, dataCenter/ansible/nodes-srm-docker.yml, dataCenter/ansible/roles/srm-docker/handlers/main.yml, dataCenter/ansible/roles/srm-docker/tasks/main.yml, dataCenter/ansible/roles/srm-docker/templates/etc_default_docker.j2
Using a playbook with 
- a task to update /etc/default/docker
- a template docker config file
- a notify handler to restart docker
=> Configure and restart docker

dataCenter/ansible/README.md, dataCenter/ansible/roles/srm-sessions/files/prd.Sessions.config, dataCenter/ansible/roles/srm-sessions/tasks/main.yml, dataCenter/ansible/srm-sessions.yml
=> sessions, config, start

dataCenter/ansible/README.md, dataCenter/ansible/all-apt-docker.yml, dataCenter/ansible/all-pip-docker-py.yml, dataCenter/ansible/all-ssh-addkey.yml, dataCenter/ansible/roles/srm-consul/tasks/main.yml, dataCenter/ansible/srm-all.yml, dataCenter/ansible/srm-consul.yml
Add consul recipe and playbook.
Common playbooks are now either "all" or just "nodes".
=> Consul recipe

dataCenter/ansible/README.md, dataCenter/ansible/nodes-swarm-agent.yml, dataCenter/ansible/roles/srm-docker-cluster/templates/etc_default_docker_cluster.j2, dataCenter/ansible/roles/srm-swarm-agent/tasks/main.yml, dataCenter/ansible/roles/srm-swarm-master/tasks/main.yml, dataCenter/ansible/srm-master.yml, dataCenter/ansible/srm-nodes.yml
fix the docker cluster address (eth1)
add a srm-swarm-agent role and add to srm-nodes playbook so they all advertise
add a srm-swarm-master role and use in new srm-master playbook
update README
=> Docker Swarm

dataCenter/cloudformation/README.md, dataCenter/cloudformation/Vagrantfile, dataCenter/cloudformation/bootstrap-driver.sh, dataCenter/cloudformation/srm-tag.json, dataCenter/cloudformation/srm-tag.sh
Vagrantfile for a single "driver" Ubuntu VM, and
json and sh for cloudFormation of a SRM stack with TAG but no Elastic IPs
i.e. the playpen for my next Ansible bit
=> Create a tagged SRM playpen

dataCenter/ansible/README.md, dataCenter/ansible/env_SRM/group_vars/all.yml, dataCenter/ansible/env_SRM/inventory, dataCenter/ansible/env_TAG/group_vars/all.yml, dataCenter/ansible/env_local/group_vars/all.yml, dataCenter/ansible/roles/srm-frontend/tasks/main.yml
Add env_SRM inventory and vars
Parameterize the website port (8080 dev, 80 prd)
Update the README
=> Add env_SRM, minor tweaks

dataCenter/ansible/README.md, dataCenter/ansible/roles/srm-auth/tasks/main.yml
Updated role and instructions.
=> Add certificate and mount into container

localDev/dbOnlyCompose/README.MD, localDev/dbOnlyCompose/docker-compose.yml, localDev/dbOnlyCompose/down.sh, localDev/dbOnlyCompose/kill.sh, localDev/dbOnlyCompose/up.sh, localDev/dbOnlyCompose/utils/addAuthUser.sh
Splitting a db only docker compose from larger system compose.
=> Adding docker compose to bring up databases only.

dataCenter/ansible/README.md, dataCenter/ansible/roles/srm-auth/tasks/main.yml, dataCenter/ansible/roles/srm-comms/tasks/main.yml, dataCenter/ansible/roles/srm-frontend/tasks/main.yml, dataCenter/ansible/roles/srm-gateway/tasks/main.yml, dataCenter/ansible/roles/srm-sessions/tasks/main.yml, dataCenter/ansible/srm-do-infra.yml, dataCenter/ansible/srm-do-nodes.yml
Do a stop, remove, pull, start cycle.
Add two srm-do-xxx YAMLs for convenience.
=> Ansible restart fix

localDev/mysqldb/db-create.sql
Add table "events", first stab.
Also scripted the "sessions" user.
NB. This all has to be run manually against the db instance.
=> Add events table

dataCenter/ansible/env_local/group_vars/all.yml, dataCenter/ansible/roles/srm-gateway/templates/Gateway.config.j2
Ansible changes for Events:
env_local/group_vars changes the connection string for sessions, to point the dev environment to the new, scripted, sessions-dev db (prd will follow)
The gateway config template adds a new entry for the events uri
=> Events table changes

dataCenter/ansible/env_SRM/group_vars/all.yml
Switch to new sessions db, with events table
=> Events, prd

dataCenter/cloudformation/README.md, dataCenter/cloudformation/bootstrap-driver.sh, dataCenter/cloudformation/srm-tag.json, dataCenter/cloudformation/srm-tag.sh
Not the nicest diff, I'm afraid - one angly bracket looking much like another.  View all might be simpler.
Fewer security groups, but more ports for the docker one.
Fewer (i.e. only three) nodes.
=> Docker 1.12

concourse/resources/dockerSwarm/README.md, concourse/resources/dockerSwarm/resource/out
Remove the config mounting.
Only mount what each service needs.
Update README
=> Fix concourse

localDev/mysqldb/db-create.sql
The object for the POST/DELETE syntax.
=> Add meetupEvents table

localDev/mysqldb/db-create.sql
=> change meetupId to char 18 (char(36)) is interpreted as GUID.
